# Generated by Django 5.2.5 on 2026-01-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('agent', 'Agent'), ('associate', 'Associate')], default='agent', max_length=20),
        ),
    ]
